version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: pgagi-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://backend:8000
    container_name: pgagi-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend 
